#!/bin/bash
#
# collectd    Startup script for the Collectd statistics gathering daemon
# chkconfig: - 86 15
# description: Collectd is a statistics gathering daemon used to collect \
#   system information ie. cpu, memory, disk, network
# processname: collectd
# pidfile: 
# config:

# Source function library.
. /etc/init.d/functions
. /etc/profile.d/oi.sh

RETVAL=0
ARGS=""
prog="collectd"
CONFIG=$OI_ROOT/healthmonitoring/collectd/etc/collectd.conf
COLLECTD_HOME=$OI_ROOT/healthmonitoring/collectd/sbin
PIDFILE=$OI_ROOT/healthmonitoring/collectd/var/run/collectd.pid

start () {
        echo -n $"Starting $prog: "
        if [ -r "$CONFIG" ]
        then
                daemon --user collectd --pidfile $PIDFILE $COLLECTD_HOME/$prog -C "$CONFIG"
		RETVAL=$?
                echo
                [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$prog
        fi
}
stop () {
        echo -n $"Stopping $prog: "
        killproc $prog
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
}
# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status $prog
        ;;
  restart|reload)
        stop
        start
        ;;
  condrestart)
        [ -f /var/lock/subsys/$prog ] && stop && start || :
        ;;
  *)
        echo $"Usage: $0 {start|stop|status|restart|reload|condrestart}"
        exit 1
esac

exit $?

# vim:syntax=sh
