#!/bin/bash
# chkconfig: - 85 15
# description: Open Infinity Health Monitoring init script
# processname: oi3-nodechecker
# pidfile: /var/run/oi3-nodechecker.pid
# config:

# Source function library.
. /etc/rc.d/init.d/functions

# Open Infinity variables
. /etc/profile.d/oi.sh

HOSTNAME=$(hostname)
LOCKFILE=/var/lock/subsys/oi3-nodechecker
HM_HOME=$OI_ROOT/healthmonitoring/nodechecker/bin

# See how we were called.
  case "$1" in
    start)
          # Start daemon.
          $HM_HOME/start
          RETVAL=$?
	  [ $RETVAL -eq 0 ] && touch $LOCKFILE
          ;;
    stop)
          # Stop daemons.
          $HM_HOME/stop
          echo "Waiting for shutdown.."
          sleep 2

          RETVAL=$?
          [ $RETVAL -eq 0 ] && rm -f $LOCKFILE
          ;;
    restart)
          $0 stop
          $0 start
          ;;
    condrestart)
         [ -e $LOCKFILE ] && $0 restart
         ;;
    status)
          status oi3-nodechecker
          ;;
    *)
          echo "Usage: $0 {start|stop|restart|status}"
          exit 1
  esac

exit 0
